---
run:
  deadline: 30m

linters:
  enable-all: true
  disable:
    - gochecknoglobals  # unreliable
    - golint            # covered by revive
    - interfacer        # deprecated
    - lll               # line length check
    - stylecheck        # covered by revive
    - typecheck         # See golangci/golangci-lint#419
    - varcheck          # unreliable
    - varnamelen        # Too opinionated about var length
    - funlen            # function length checks
    - godot             # Don't mandate periods at end of comments
    - nlreturn          # Too opioniated about whitespace
    - wsl               # Way to opinionated
    - whitespace        # Too opinionated about whitespace
    - wrapcheck         # XXX should we switch to wrapped errors etc?
    - goerr113          # XXX should we switch to wrapped errors etc?
    - exhaustivestruct  # Too opinionated
    - gofumpt           # Too opinionated about whitespace
    - gomnd             # We use plenty of magic constants
    - scopelint         # Obsoleted
    - gocognit          # Too opinionated on existing code
    - gocyclo           # Too opinionated on existing code
    - maligned          # Too opinionated on existing structs
    - nestif            # Too opinionated on existing code
    - gomoddirectives   # We use replacements in go mod
    - cyclop            # Raises warnings even for relatively simple functions
    - ifshort           # Proposes changes which make code less readable
    - maintidx          # Raises warnings even for relatively simple functions

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# yetus expects stable output from linter
# that is we should return all errors
# not only the first hit
output:
  uniq-by-line: false
