name: 'Setup environment to run eden tests'
description: 'Setup building dependencies'

inputs:
  eve_artifact_name:
    type: string
  artifact_run_id:
    type: string
    
runs:
  using: 'composite'
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Check
      run: |
        for addr in $(ip addr list|sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
        do
            if echo "$addr" | grep -q -E "10.11.(12|13).[0-9]+"; then
              echo "$addr overlaps with test"; exit 1
            fi
        done
        df -h
        sudo swapoff -a
        free
      shell: bash
      working-directory: "./eden"
    - name: Install Packages
      run: |
        sudo add-apt-repository ppa:stefanberger/swtpm-jammy
        sudo apt install -y qemu-utils qemu-system-x86 jq swtpm util-linux socat
      shell: bash
    - name: Build tests
      run: |
        make build-tests
      shell: bash
      working-directory: "./eden"
    - name: Download artifact if specified
      if: inputs.eve_artifact_name != ''
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ github.token }}
        name: ${{ inputs.eve_artifact_name }}
        path: artifacts  # this is the directory where it will put the artifact, not its name
        run-id: ${{ inputs.artifact_run_id }}
    - name: Load containers to docker if specified
      if: inputs.eve_artifact_name != ''
      run: |
        docker load -q -i artifacts/${{ inputs.eve_artifact_name }}.tar
        docker image ls
      shell: bash
