name: 'Run specified Eden test workflow'
description: 'Setup Eden run specified test from workflow and publish logs'

inputs:
  file_system:
    required: true
    type: string
  tpm_enabled:
    required: true
    type: bool
  suite:
    required: true
    type: string
  eve_image:
    type: string
  eve_artifact_name:
    type: string
  artifact_run_id:
    type: string
  require_virtualization:
    type: bool
  docker_account:  # if not provided: use anonymous docker user
    type: string
    required: false
    default: ''
  docker_token:
    type: string
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
      with:
        proc_trace_sys_enable: true
        comment_on_pr: false
    - name: Login to Docker Hub
      if: inputs.docker_account != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_account }}
        password: ${{ inputs.docker_token }}
    - name: Setup Environment
      uses: ./eden/.github/actions/setup-environment
      with:
        file_system: ${{ inputs.file_system }}
        tpm_enabled: ${{ inputs.tpm_enabled }}
        eve_image: ${{ inputs.eve_image }}
        eve_artifact_name: ${{ inputs.eve_artifact_name }}
        artifact_run_id: ${{ inputs.artifact_run_id }}
        require_virtualization: ${{ inputs.require_virtualization }}
    - name: Run tests
      run: EDEN_TEST_STOP=n ./eden test ./tests/workflow -s ${{ inputs.suite }} -v debug
      shell: bash
      working-directory: "./eden"
    - name: Collect info
      if: failure()
      uses: ./eden/.github/actions/collect-info
    - name: Collect logs
      if: always()
      uses: ./eden/.github/actions/publish-logs
      with:
        report_name: eden-report-${{ inputs.suite }}-tpm-${{ inputs.tpm_enabled }}-${{ inputs.file_system }}
    - name: Clean up after test
      if: always()
      run: |
        ./eden stop
        make clean >/dev/null
        docker system prune -f -a >/dev/null
      shell: bash
      working-directory: "./eden"
