name: 'Run specified Eden test workflow'
description: 'Setup Eden run specified test from workflow and publish logs'

inputs:
  file_system:
    required: true
    type: string
  tpm_enabled:
    required: true
    type: bool
  suite:
    required: true
    type: string
  eve_image:
    type: string

runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      uses: ./eden/.github/actions/setup-environment
      with:
        file_system: ${{ inputs.file_system }}
        tpm_enabled: ${{ inputs.tpm_enabled }}
        eve_image: ${{ inputs.eve_image }}
    - name: Run tests
      run: EDEN_TEST_STOP=n ./eden test ./tests/workflow -s ${{ inputs.suite }} -v debug
      shell: bash
      working-directory: "./eden"
    - name: Collect info
      if: failure()
      uses: ./eden/.github/actions/collect-info
    - name: Collect logs
      if: always()
      uses: ./eden/.github/actions/publish-logs
      with:
        file_system: ${{ inputs.file_system }}
        tpm_enabled: ${{ inputs.tpm_enabled }}
    - name: Clean up after test
      if: always()
      run: |
        ./eden stop
        make clean
        docker system prune -f -a
      shell: bash
      working-directory: "./eden"
